app <- ShinyDriver$new("../")
app$snapshotInit("aboutModel")

app$snapshot()
app$setInputs(aboutModelBtn = "click")
app$snapshot()
app$setInputs(AboutModel = "aboutMI")
app$setInputs(aboutModelBtn = "click")
app$snapshot()
app$setInputs(AboutModel = "aboutRF")
app$setInputs(aboutModelBtn = "click")
app$snapshot()
app$setInputs(AboutModel = "aboutCDiff")
app$setInputs(aboutModelBtn = "click")
app$setInputs(AboutModel = "aboutd90")
app$setInputs(aboutModelBtn = "click")
app$setInputs(AboutModel = "aboutInfection")
app$setInputs(aboutModelBtn = "click")
app$snapshot()
app$setInputs(AboutModel = "aboutCI")
app$setInputs(aboutModelBtn = "click")
app$snapshot()
