app <- ShinyDriver$new("../")
app$snapshotInit("modelTest")

app$snapshot()
app$setInputs(modelCompare = "compareMI")
app$snapshot()
app$setInputs(modelCompare = "compareRF")
app$snapshot()
app$setInputs(modelCompare = "compareCDiff")
app$snapshot()
app$setInputs(modelCompare = "compared90")
app$snapshot()
app$setInputs(modelCompare = "compareInfection")
app$snapshot()
app$setInputs(modelCompare = "compareCI")
app$snapshot()
app$snapshot()
app$snapshot()
