app <- ShinyDriver$new("../")
app$snapshotInit("riskPage")

app$snapshot()
app$setInputs(Age = 100)
app$setInputs(Age = 81)
app$setInputs(CIHD = "1")
app$setInputs(HT = "1")
app$setInputs(HCD = "1")
app$setInputs(RFbtn = "click")
app$setInputs(Age = 91)
app$setInputs(RFbtn = "click")
app$setInputs(RFbtn = "click")
app$setInputs(Sex = "0.222222222")
app$setInputs(Hyperthyroidism = "1")
app$setInputs(Hypothyroidism = "1")
app$setInputs(RFbtn = "click")
app$setInputs(AF = "1")
app$setInputs(IDDM = "1")
app$setInputs(RFbtn = "click")
app$setInputs(MIbtn = "click")
app$setInputs(TIAbtn = "click")
app$setInputs(CIHD = "0")
app$setInputs(Hypothyroidism = "0")
app$setInputs(AF = "0")
app$setInputs(TIAbtn = "click")
app$snapshot()
app$setInputs(NIDDM = "1")
app$setInputs(CDiffbtn = "click")
app$snapshot()
app$setInputs(Age = 58)
app$setInputs(d90btn = "click")
app$setInputs(CIbtn = "click")
app$snapshot()
app$setInputs(Hyperthyroidism = "0")
app$setInputs(IDDM = "0")
app$setInputs(CIbtn = "click")
app$setInputs(Infectionbtn = "click")
app$snapshot()
app$setInputs(Age = 102)
app$setInputs(Infectionbtn = "click")
app$setInputs(d90btn = "click")
app$setInputs(Age = 107)
app$setInputs(Age = 108)
app$setInputs(d90btn = "click")
app$setInputs(CIHD = "1")
app$setInputs(Hyperthyroidism = "1")
app$setInputs(Hypothyroidism = "1")
app$setInputs(d90btn = "click")
app$setInputs(Sex = "0.1111111111")
app$setInputs(d90btn = "click")
app$setInputs(d90btn = "click")
app$setInputs(IDDM = "1")
app$setInputs(AF = "1")
app$setInputs(d90btn = "click")
app$setInputs(HC = "1")
app$setInputs(Osteoporosis = "1")
app$setInputs(Dementia = "1")
app$setInputs(d90btn = "click")
app$setInputs(Infectionbtn = "click")
app$snapshot()
