app <- ShinyDriver$new("../", loadTimeout = 10000)
app$snapshotInit("Startpage")

app$setInputs(yearlyStats = "yearlyTIA")
app$snapshot()
app$setInputs(yearlyStats = "yearlyMI")
app$snapshot()
app$setInputs(yearlyStats = "yearlyRF")
app$snapshot()
app$setInputs(yearlyStats = "yearlyCDiff")
app$snapshot()
app$setInputs(yearlyStats = "yearlyd90")
app$snapshot()
app$setInputs(yearlyStats = "yearlyCI")
app$snapshot()
app$setInputs(yearlyStats = "yearlyInfection")
app$snapshot()
app$snapshot()
app$snapshot()
